language: python
addons:
  apt:
    packages:
      - zsh

matrix:
  allow_failures:
    - python: nightly
    - python: pypy3
  include:
    - python: "3.5"
    - python: "3.4"
    - python: "3.3"
    - python: "3.2"
    - python: nightly
    - python: pypy3
  fast_finish: true

install: |
  if [ -z "$PYTHON" ]
  then
    [ "$TRAVIS_PYTHON_VERSION" = "3.2" ] && pip install coverage==3.7.1
    pip install -r requirements.txt
  fi

script: |
  tox
